### ISSUE TITLE
engines entry on package.json

### ISSUE THREAD

**Issue by vitordino** [wasim919/fnm#1]
would be nice to know which node/npm you are using, please use the [engines entry on package.json](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines), probably something like:
```json
{
  "engines": {
    "node": "^14",
    "npm": "8.3.1"
  },
}
```

**Comment by wasim919** [comment]
I have added the engines property. Earlier, I had forgotten to push the latest changes.

**Comment by vitordino** [comment]
great, feel free to close this
